// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[storeSlug]" | "/[storeSlug]/cart" | "/[storeSlug]/checkout" | "/[storeSlug]/checkout/success" | "/[storeSlug]/products" | "/[storeSlug]/products/[productSlug]" | "/admin/stores" | "/auth/login" | "/dashboard" | "/dashboard/orders" | "/dashboard/orders/[orderId]" | "/dashboard/products" | "/dashboard/products/[productId]/edit" | "/dashboard/products/new" | "/test"
type AppRouteHandlerRoutes = "/api/checkout" | "/api/cloudinary/sign" | "/api/orders/[orderId]/status" | "/api/products" | "/api/products/[productId]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[storeSlug]": { "storeSlug": string; }
  "/[storeSlug]/cart": { "storeSlug": string; }
  "/[storeSlug]/checkout": { "storeSlug": string; }
  "/[storeSlug]/checkout/success": { "storeSlug": string; }
  "/[storeSlug]/products": { "storeSlug": string; }
  "/[storeSlug]/products/[productSlug]": { "storeSlug": string; "productSlug": string; }
  "/admin": {}
  "/admin/stores": {}
  "/api/checkout": {}
  "/api/cloudinary/sign": {}
  "/api/orders/[orderId]/status": { "orderId": string; }
  "/api/products": {}
  "/api/products/[productId]": { "productId": string; }
  "/auth/login": {}
  "/dashboard": {}
  "/dashboard/orders": {}
  "/dashboard/orders/[orderId]": { "orderId": string; }
  "/dashboard/products": {}
  "/dashboard/products/[productId]/edit": { "productId": string; }
  "/dashboard/products/new": {}
  "/test": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
